### ISSUE TITLE
Unable to re-activate license

### ISSUE THREAD

**Issue by udayk45** [davidwernhart/AlDente-Charge-Limiter#1017]
**Describe the bug**
After upgrading to macOS Ventura, ai dente showed popup to recheck license. But it failed always. So tried re-installing but unable to activate the license after reinstall as well.

**Expected behavior**

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.
<img width="282" alt="Screenshot 2023-08-02 at 8 34 16 PM" src="https://github.com/davidwernhart/AlDente-Charge-Limiter/assets/108542530/1997b4f7-9fe3-41d1-9895-d0e8f6c9362d">

**MacBook (please complete the following information):**
 - MacBook model - Apple M1 Pro
 - macOS version - 13.4.1 
 - AlDente Pro or AlDente Free - AlDente Pro
 - AlDente Version - AlDente Pro

**Comment by MatthiasKerbl** [comment]
Hi @udayk45,

Most of the time, this issue occurs because your device is unable to connect to our license server. Are you using a VPN or Firewall application that might block this connection? If so, please try to disable it and see if the activation works afterward. Furthermore, some countries are blocking the connection to the licensing server as well. Therefore, also try to use a VPN to connect to the licensing server through different countries.

Best,
Matthias

**Comment by udayk45** [comment]
With VPN is started working again.
