### ISSUE TITLE
USB accessories have been disabled

### ISSUE THREAD

**Issue by YangWangcc** [davidwernhart/AlDente-Charge-Limiter#839]
Since I downloaded the software, when I unplugged the power box cover at night and opened it the next morning, the pop-up window "USB accessories have been disabled, unplug the accessories that consume too much power to re enable the USB device" appeared, but no USB was connected to the MacBook. Whether this software causes this problem.

**Comment by MatthiasKerbl** [comment]
Hi @YangWangcc,

Please fill out the following questions first.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**MacBook (please complete the following information):**
 - MacBook model (https://support.apple.com/en-us/HT201608)
 - macOS version (https://support.apple.com/en-us/HT201260)
 - AlDente Pro or AlDente Free?
 - AlDente Version?
 - List of all enabled/disabled settings in AlDente:

**Additional context**
Add any other context about the problem here.
