### ISSUE TITLE
Prevent "Paused to save battery" messages, because Al Dente is not charging battery?

### ISSUE THREAD

**Issue by mikebore** [davidwernhart/AlDente-Charge-Limiter#878]
Certain processes eg Photos syncing, and Mailbox rebuilding are (sometimes?) automatically paused  because machine thinks it is on Battery power because Al Dente is preventing charging. 

Is there an AlDente, or a global setting which will stop this happening? 

Thanks for great app!

**Comment by MatthiasKerbl** [comment]
Hi @mikebore,

Usually, when AlDente paused charging, the MacBook does not believe it is on battery power. It is just not charging further. As seen in the following screenshot:
<img width="346" alt="charging paused" src="https://user-images.githubusercontent.com/33470003/216047581-9b70e89f-113b-4cce-9d5d-20e4e865b441.png">

Are you still experiencing some background processes being paused due to the "Paused to save battery" message?

Also, during the Discharge mode, the MacBook actually switches battery power.

Cheers,
Matthias

**Comment by mikebore** [comment]
I noticed the problem while setting up a new computer which involved a lot of Photos and email syncing. The issue has not recurred since I finished those.

Anyway your reply confirms there isn't a setting I have missed.
