### ISSUE TITLE
MacBook Air M2 no sailing

### ISSUE THREAD

**Issue by BlackDiceagain** [davidwernhart/AlDente-Charge-Limiter#934]
Hi my aldente Pro is to going to sailing Mode. I set the max charging limit to 85% and in sailing mode the difference to 5%. But the MacBook is not going to 80%. The battery settings say: battery not charging and power over power adapter. Does anyone know where the problem could be?

**Comment by MatthiasKerbl** [comment]
Hi @BlackDiceagain,

Please take a look at our [FAQ](https://apphousekitchen.com/faq/) and [blog](https://apphousekitchen.com/feature-explanation-sailing-mode/).

_The Sailing Mode is not intended to actively discharge your battery. Therefore, your MacBook will barely lose any energy even in Sailing Mode, since the power brick is the main source of energy. So do not worry when the battery percentage does not change even if the Sailing Mode is activated. Sailing Mode is still doing its thing. You can read more about what the Sailing Mode actually does here: https://apphousekitchen.com/feature-explanation-sailing-mode/_

Cheers,
Matthias
