### ISSUE TITLE
Says 83% when plugged in, when I unplug it drops immediately to 7% or less

### ISSUE THREAD

**Issue by jimsefton** [davidwernhart/AlDente-Charge-Limiter#951]
This does not happen when I don't have Aldente running so I don't think it is a battery issue. 

Edit: It seems to be when the computer has been asleep. I wake it up and the battery says 83%... ah hour later I unplug it to take it somewhere and it seems like the battery is almost depleted. When I plug it back in it charges as normal.

**Comment by MatthiasKerbl** [comment]
Hi @jimsefton,

Please fill out the following questions so that I can assess your situation more thoroughly:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See the error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**MacBook (please complete the following information):**
 - MacBook model (https://support.apple.com/en-us/HT201608)
 - macOS version (https://support.apple.com/en-us/HT201260)
 - AlDente Pro or AlDente Free?
 - AlDente Version?
 - List of all enabled/disabled settings in AlDente:

**Additional context**
Add any other context about the problem here.
